version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 3
  identical-code:
    config:
      threshold: 3
plugins:
  rubocop:
    enabled: false
  eslint:
    enabled: true
    checks:
      for-direction:
        enabled: false
      node/no-extraneous-import:
        enabled: false
      node/no-missing-import:
        enabled: false
      node/no-missing-require:
        enabled: false
      node/no-unpublished-import:
        enabled: false
      node/prefer-global/buffer:
        enabled: false
      node/prefer-global/process:
        enabled: false
      node/prefer-global/url-search-params:
        enabled: false
      node/prefer-global/url:
        enabled: false
      no-buffer-constructor:
        enabled: false      no-storage/no-browser-storage:
        enabled: false
  csslint:
    enabled: false
exclude_patterns:
- "**/node_modules/"
- "**/test/"
