engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 68
  eslint:
    enabled: true
    channel: "eslint-3"
    config:
      config: .eslint.yml
  fixme:
    enabled: true
  markdownlint:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.md"
exclude_paths:
- node_modules/
