root: true

env:
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    globalReturn: false
    jsx: false
    modules: false
  ecmaVersion: 6
  sourceType: script

plugins:
- node
- no-storage
- security
- xss

extends: [eslint:recommended, plugin:node/recommended, plugin:security/recommended]

# http://eslint.org/docs/rules/
rules:
  # Possible Errors
  for-direction: 2
  no-await-in-loop: 2
  no-console: 0
  no-extra-parens: 2
  no-inner-declarations: [2, functions]
  no-prototype-builtins: 2
  no-template-curly-in-string: 2
  no-unsafe-negation: 2
  valid-jsdoc: 2

  # Best Practices
  accessor-pairs: 2
  array-callback-return: 2
  block-scoped-var: 2
  class-methods-use-this: 2
  complexity: [2, 12]
  consistent-return: 2
  curly: 2
  default-case: 2
  dot-location: 2
  dot-notation: 2
  eqeqeq: 2
  guard-for-in: 2
  no-alert: 2
  no-caller: 2
  no-div-regex: 2
  no-else-return: 2
  no-empty-function: 2
  no-eq-null: 2
  no-eval: 2
  no-extend-native: 2
  no-extra-bind: 2
  no-extra-label: 2
  no-floating-decimal: 2
  no-implicit-coercion: 2
  no-implicit-globals: 2
  no-implied-eval: 2
  no-iterator: 2
  no-labels: 2
  no-lone-blocks: 2
  no-loop-func: 2
  no-multi-spaces: 2
  no-multi-str: 2
  no-new-func: 2
  no-new-wrappers: 2
  no-new: 2
  no-octal-escape: 2
  no-param-reassign: 2
  no-proto: 2
  no-restricted-properties: 2
  no-return-assign: 2
  no-return-await: 2
  no-self-compare: 2
  no-sequences: 2
  no-throw-literal: 2
  no-unmodified-loop-condition: 2
  no-unused-expressions: 2
  no-useless-call: 2
  no-useless-concat: 2
  no-useless-return: 2
  no-void: 2
  no-warning-comments: 2
  no-with: 2
  prefer-promise-reject-errors: 2
  radix: 2
  require-await: 2
  vars-on-top: 2
  wrap-iife: 2

  # Strict
  strict: [2, "global"]

  # Variables
  init-declarations: 2
  no-catch-shadow: 2
  no-label-var: 2
  no-restricted-globals: 2
  no-shadow-restricted-names: 2
  no-shadow: 2
  no-undef-init: 2
  no-use-before-define: 2

  # Node.js and CommonJS
  callback-return: 2
  global-require: 0
  handle-callback-err: 2
  no-buffer-constructor: 2
  no-mixed-requires: 2
  no-new-require: 2
  no-path-concat: 2
  no-process-env: 2
  no-process-exit: 2
  no-restricted-modules: 2
  no-sync: 2

  # Stylistic Issues
  array-bracket-spacing: 2
  block-spacing: 2
  brace-style: 2
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  consistent-this: 2
  eol-last: 2
  func-call-spacing: 2
  func-name-matching: 2
  func-style: 2
  id-blacklist: 2
  id-match: 2
  indent: ["error", 2]
  jsx-quotes: 2
  key-spacing: 2
  keyword-spacing: 2
  linebreak-style: 2
  max-depth: 2
  max-len: ["warn", {"code": 99, "tabWidth": 2, "ignoreComments": true, "ignoreUrls": true, "ignoreStrings": true, "ignoreTemplateLiterals": true, "ignoreRegExpLiterals": true}]
  max-lines: ["error", {"max": 150, "skipBlankLines": true, "skipComments": true}]
  max-nested-callbacks: 2
  max-params: 2
  max-statements-per-line: 2
  max-statements: [2, 76]
  multiline-ternary: 0
  new-cap: 2
  new-parens: 2
  newline-per-chained-call: 2
  no-array-constructor: 2
  no-bitwise: 2
  no-continue: 2
  no-lonely-if: 2
  no-multiple-empty-lines: 2
  no-negated-condition: 2
  no-nested-ternary: 2
  no-new-object: 2
  no-plusplus: 2
  no-restricted-syntax: 2
  no-tabs: 2
  no-trailing-spaces: 2
  no-underscore-dangle: 2
  no-unneeded-ternary: 2
  no-whitespace-before-property: 2
  nonblock-statement-body-position: 2
  object-curly-newline: 2
  object-curly-spacing: 2
  operator-assignment: 2
  operator-linebreak: 2
  quote-props: 2
  quotes: 2
  require-jsdoc: 2
  semi-spacing: 2
  semi: 2
  sort-keys: 2
  sort-vars: 2
  space-before-blocks: 2
  space-in-parens: 2
  space-infix-ops: 2
  space-unary-ops: 2
  spaced-comment: 2
  template-tag-spacing: 2
  unicode-bom: 2
  wrap-regex: 2

  # ECMAScript 6
  arrow-body-style: 2
  arrow-parens: 2
  arrow-spacing: 2
  generator-star-spacing: 2
  no-confusing-arrow: 2
  no-duplicate-imports: 2
  no-restricted-imports: 2
  no-useless-computed-key: 2
  no-useless-constructor: 2
  no-useless-rename: 2
  no-var: 2
  object-shorthand: 2
  prefer-const: 2
  prefer-numeric-literals: 2
  prefer-rest-params: 2
  prefer-spread: 2
  prefer-template: 2
  rest-spread-spacing: 2
  sort-imports: 2
  symbol-description: 2
  template-curly-spacing: 2
  yield-star-spacing: 2

  # node
  # using recommended; https://github.com/mysticatea/eslint-plugin-node
  node/no-extraneous-import: 2
  node/no-missing-import: 2
  node/no-missing-require: 0
  node/no-unpublished-import: 2
  # style
  node/exports-style: 0
  node/prefer-global/buffer: 2
  node/prefer-global/process: 2
  node/prefer-global/url-search-params: 2
  node/prefer-global/url: 2


  # no-storage
  no-storage/no-browser-storage: 2

  # security
  # using recommended; https://github.com/nodesecurity/eslint-plugin-security

  # xss
  xss/no-location-href-assign: 2
  xss/no-mixed-html: 0
