---
branches:
  except:
  - gh-pages
os: linux
git:
  depth: 12
  submodules: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '14'
- '15'
- '16'
- '18'
matrix:
  fast_finish: true
before_install:
- npm set progress=false ; npm install -g grunt-cli
