branches:
  except:
  - gh-pages
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '7'
- '8'
- '9'
- '10'
before_install:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: VHmFYjUHeMY9dslDhki0w7bFMkcfJxKw50zmOkMmaw4setuahgFERweS8gOuw/X3R+NuNpbW4Rzg4q/fDOrr0/ZHZJbEnFNxbS/l6ulqhte6/L7HTswEJMZaPTSssrJ7Gwhp3VvWQhVGvBq2PlS4yytd61DLnxBU3jWBoQbw4mk=
