branches:
  except:
  - gh-pages
sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4.4'
- '5.10'
before_script:
- npm set progress=false ; npm install -g grunt-cli
notifications:
  slack:
    secure: WFZX56KOZCVJn1EQAsY3ITF4nGXiRikd30+ExlFrSiDj75LG++fEL9vrV5mvErjj23283YfNha++kFcelSl7G1edk6/ykB8bP5pXc/S2XbgvYJW3lD6bx8IjsdJeRuCSOyK2i1QfToMGmEx6DBb+Tn0E0lX4Mv/ujIm/YkHlFQk=
