---
root: true

env:
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    globalReturn: false
    jsx: false
    modules: true
  ecmaVersion: 6
  sourceType: script

plugins:
- json
- node

extends: [eslint:recommended, plugin:json/recommended, plugin:node/recommended]

# http://eslint.org/docs/rules/
rules:
  # Possible Errors
  for-direction: "error"
  no-await-in-loop: "error"
  no-console: "off"
  no-inner-declarations: ["error", functions]
  no-prototype-builtins: "error"
  no-template-curly-in-string: "error"
  no-unsafe-negation: "error"

  # Best Practices
  accessor-pairs: "error"
  array-callback-return: "error"
  block-scoped-var: "error"
  class-methods-use-this: "error"
  complexity: ["error", 12]
  consistent-return: "error"
  curly: "error"
  default-case: "error"
  dot-notation: "error"
  eqeqeq: "error"
  guard-for-in: "error"
  no-alert: "error"
  no-caller: "error"
  no-div-regex: "error"
  no-else-return: "error"
  no-empty-function: "error"
  no-eq-null: "error"
  no-eval: "error"
  no-extend-native: "error"
  no-extra-bind: "error"
  no-extra-label: "error"
  no-implicit-coercion: "error"
  no-implicit-globals: "error"
  no-implied-eval: "error"
  no-iterator: "error"
  no-labels: "error"
  no-lone-blocks: "error"
  no-loop-func: "error"
  no-multi-str: "error"
  no-new-func: "error"
  no-new-wrappers: "error"
  no-new: "error"
  no-octal-escape: "error"
  no-param-reassign: "error"
  no-proto: "error"
  no-restricted-properties: "error"
  no-return-assign: "error"
  no-self-compare: "error"
  no-sequences: "error"
  no-throw-literal: "error"
  no-unmodified-loop-condition: "error"
  no-unused-expressions: "error"
  no-useless-call: "error"
  no-useless-concat: "error"
  no-useless-return: "error"
  no-void: "error"
  no-warning-comments: "error"
  no-with: "error"
  prefer-promise-reject-errors: "error"
  radix: "error"
  require-await: "error"
  vars-on-top: "error"

  # Strict
  strict: ["error", "global"]

  # Variables
  init-declarations: "error"
  no-shadow: "error"
  no-label-var: "error"
  no-restricted-globals: "error"
  no-shadow-restricted-names: "error"
  no-undef-init: "error"
  no-use-before-define: "error"

  # Stylistic Issues
  consistent-this: "error"
  func-name-matching: "error"
  func-style: "error"
  id-denylist: "error"
  id-match: "error"
  max-depth: "error"
  max-lines: ["error", {"max": 150, "skipBlankLines": true, "skipComments": true}]
  max-nested-callbacks: "error"
  max-params: "error"
  max-statements: ["error", 76]
  new-cap: "error"
  no-array-constructor: "error"
  no-bitwise: "error"
  no-continue: "error"
  no-lonely-if: "error"
  no-negated-condition: "error"
  no-nested-ternary: "error"
  no-object-constructor: "error"
  no-plusplus: "error"
  no-restricted-syntax: "error"
  no-underscore-dangle: "error"
  no-unneeded-ternary: "error"
  operator-assignment: "error"
  sort-keys: "error"
  sort-vars: "error"
  unicode-bom: "error"

  # ECMAScript 6
  arrow-body-style: "error"
  no-duplicate-imports: "error"
  no-restricted-imports: "error"
  no-useless-computed-key: "error"
  no-useless-constructor: "error"
  no-useless-rename: "error"
  no-var: "error"
  object-shorthand: "error"
  prefer-const: "error"
  prefer-numeric-literals: "error"
  prefer-rest-params: "error"
  prefer-spread: "error"
  prefer-template: "error"
  sort-imports: "error"
  symbol-description: "error"

  # node using recommended; https://github.com/mysticatea/eslint-plugin-node
  node/prefer-global/buffer: "error"
  node/prefer-global/process: "error"
  node/prefer-global/url-search-params: "error"
  node/prefer-global/url: "error"
