---
ignore: |
  codeql-analysis.yml
  linter.yml

yaml-files:
  - '.*.yml'
  - '*.yaml'
  - '*.yml'

rules:
  brackets:
    forbid: false
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 1
  indentation:
    spaces: consistent
    indent-sequences: consistent
    check-multi-line-strings: false
  line-length:
    max: 92
    level: warning
